### PR TITLE
Change license to Apache-2.0

### PR DESCRIPTION
**Pull request by paulhauner**
This repository was previously licensed as `MIT/Apache-2.0`. Given that the AMCL library is Apache 2.0, I don't think is it permitted to add the MIT license.

I will seek @lovesh's input on this, as I assume he did the initial `MIT/Apache-2.0` licensing.

### CODE REVIEW

**Comment by lovesh** [comment]
Hi Paul. I don't see the dual license in my fork, I only see Apache-2 license. Can you please point me to where it says MIT? Maybe at some point I had then MIT and then removed it. If i ever had then it would have been a mistake on my point.

**Comment by lovesh** [comment]
@paulhauner Correction to my previous response. I have removed the MIT license part from the toml file. Thanks for pointing that.

**Comment by paulhauner** [comment]
It would be great if we could get all contributors to agree they understand their works are licensed under Apache-2.0 not dual Apache-2.0/MIT. 

- [ ] @kirk-baird
- [ ] @g-r-a-n-t
- [ ] @sorpaas

Could you please comment with "I approve". Thank you :)

**Comment by g-r-a-n-t** [comment]
I approve :)

**Comment by sorpaas** [comment]
I approve :)

**Comment by kirk-baird** [comment]
I approve :)

**Comment by paulhauner** [comment]
Thanks everyone!

**Pull request merged**
